### ISSUE TITLE
StoreService method hasAspect

### ISSUE THREAD

**Issue by csalvioiss** [consiglionazionaledellericerche/storage-cloud#2]
Il metodo per l'implementazione con Driver FileSystem va in ClassCastException come di seguito:
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at it.cnr.si.spring.storage.StoreService.hasAspect(StoreService.java:300)

**Comment by mspasiano** [comment]
Issue closed on version 2.0.4
